baseURL = "https://twentysixdigitalprinting.com"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "pr"

[build]
  writeStats = true

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "Rp"
    reting = ""